package markdown

import (
	"bytes"
	"fmt"
	"slices"

	"github.com/shutx-net/micawber/core"
)

// Bytes serializes the document back to the bytes of a Markdown file.
//
// The result is the concatenation of the five slots the parser filled in --
// Layout.BOM, Layout.Open, the front-matter block, Layout.Close and
// Content.Body -- so a document parsed and serialized without being edited is
// byte-identical to the file it came from. A zero Layout means the canonical
// delimiters for the content's format.
//
// The block itself is emitted verbatim while the content's Fields still say what
// it says, and re-encoded once they do not. See [Document] and the package
// documentation for what a re-encode preserves.
//
// The returned error matches [core.ErrInvalid] when the front matter is not well
// formed, or when the content has no front matter but a body that would itself
// be read as opening a block.
func (d Document) Bytes() ([]byte, error) {
	fm := d.Content.FrontMatter

	// core's own rules, rather than a second copy of them here. Content.Validate
	// is deliberately not called: Parse leaves Path zero for the caller to set,
	// and a document's address is not this package's business.
	if err := fm.Validate(); err != nil {
		return nil, fmt.Errorf("markdown: cannot serialize: %w", err)
	}
	if fm.Format == core.FrontMatterNone && bodyOpensFrontMatter(d.Content.Body) {
		return nil, fmt.Errorf("markdown: cannot serialize: the content has no front matter, but its body would be read as opening a block: %w", core.ErrInvalid)
	}

	layout := d.Layout
	if layout.IsZero() {
		layout = defaultLayout(fm.Format)
	}

	block, err := frontMatterBlock(fm, layout.lineEnding())
	if err != nil {
		return nil, err
	}
	block = terminateBlock(block, layout, d.Content.Body)

	var mark []byte
	if layout.BOM {
		mark = []byte(bom)
	}

	// The identity the whole package rests on, in one line so that reading it is
	// enough to check it.
	return slices.Concat(mark, []byte(layout.Open), block, []byte(layout.Close), d.Content.Body), nil
}

// Format serializes a [core.Content] that did not come from Parse, using the
// canonical delimiters for its front-matter format.
//
// It is the entry point for a document assembled by hand -- a new document, or
// one whose Layout the caller did not keep. A document that was parsed should be
// written back with [Document.Bytes] instead, so that its delimiters, line
// endings and any byte-order mark survive.
//
// The returned error matches [core.ErrInvalid] when the content cannot be
// serialized to a document that would parse back to it.
func Format(c core.Content) ([]byte, error) {
	// The zero Layout is the canonical shape, so there is nothing to supply.
	return Document{Content: c}.Bytes()
}

// frontMatterBlock returns the bytes to emit between the delimiters. It is the
// only place in the package that decides between authored and generated bytes,
// so the three cases are three named arms rather than a nested conditional: this
// is the code to read to check the diff-fidelity claim.
//
// ending is the line terminator the document was written with; a generated block
// is converted to it, and an authored one is never touched.
func frontMatterBlock(fm core.FrontMatter, ending string) ([]byte, error) {
	if fm.Format == core.FrontMatterNone {
		// Validate has already ruled out Raw and Fields on this path.
		return nil, nil
	}
	cdc, ok := codecFor(fm.Format)
	if !ok {
		return nil, fmt.Errorf("markdown: %s front matter: %w", fm.Format, core.ErrUnsupported)
	}

	// 1. Nothing was authored and there is nothing to write: an empty block
	//    stays empty rather than becoming an encoded empty mapping. JSON is the
	//    exception, because its braces are the only thing that says the format
	//    is JSON, so dropping them would drop the front matter.
	if len(fm.Raw) == 0 && len(fm.Fields) == 0 {
		if fm.Format == core.FrontMatterJSON {
			return []byte("{}"), nil
		}
		return fm.Raw, nil
	}

	// 2. The authored block still says what Fields says: emit it verbatim, byte
	//    for byte. This is the common CMS write -- a body edit with untouched
	//    metadata -- and the comparison is what makes the passthrough safe
	//    rather than a guess.
	if len(fm.Raw) > 0 {
		authored, err := cdc.decode(fm.Raw)
		if err != nil {
			return nil, fmt.Errorf("markdown: cannot serialize: %w", err)
		}
		if fieldsEqual(authored, fm.Fields) {
			return fm.Raw, nil
		}
	}

	// 3. The fields have been edited, or there was never an authored block.
	//    Re-encode, handing the codec the authored bytes so that everything the
	//    edit did not touch keeps its order, its comments and its quoting.
	encoded, err := cdc.encode(fm.Fields, fm.Raw)
	if err != nil {
		return nil, err
	}
	// Whether the block needs a terminator of its own is terminateBlock's
	// question, because only it knows what follows: for JSON the terminator
	// belongs to Layout.Close, not to the object text.
	return applyLineEnding(encoded, ending), nil
}

// terminateBlock ends the block's last line when something would otherwise be
// glued to it.
//
// Parse never produces such a block -- a delimiter-fenced block always ends with
// the terminator of its last line, and a JSON object is followed by whatever
// Layout.Close holds -- so this only corrects a Document assembled by hand, and
// never rewrites a parsed one.
func terminateBlock(block []byte, layout Layout, body []byte) []byte {
	if len(block) == 0 || block[len(block)-1] == '\n' {
		return block
	}

	fencedByADelimiter := layout.Open != ""
	gluedToTheBody := layout.Close == "" && len(body) > 0
	if !fencedByADelimiter && !gluedToTheBody {
		return block
	}

	// Cloned rather than appended in place: block may alias the caller's Raw,
	// and writing past its length would reach into the document it came from.
	return append(bytes.Clone(block), layout.lineEnding()...)
}

// applyLineEnding converts b's line terminators to ending.
//
// The codecs emit LF. b is normalized first so that a codec which one day emits
// a CR of its own cannot produce a CRCRLF here.
func applyLineEnding(b []byte, ending string) []byte {
	if ending == "\n" {
		return b
	}
	return bytes.ReplaceAll(normalizeLF(b), []byte("\n"), []byte(ending))
}

// bodyOpensFrontMatter reports whether body would itself be read as opening a
// front-matter block.
//
// It reuses scan rather than re-implementing detection, so it cannot drift from
// the rules Parse applies. A scan failure counts as opening one: the body would
// be a block Parse then rejects, which is just as wrong as a block that changes
// what the document says.
func bodyOpensFrontMatter(body []byte) bool {
	p, err := scan(body)
	return err != nil || p.format != core.FrontMatterNone
}
